Capstone-infinite-challenge/Currex

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/views/ChattingPage/Chat.jsx

- 소켓 이용해서 채팅 보내는 코드
- 보내는 것만 구현함
- style 미완성 (오른쪽 정렬 안됨)
- 나중에 구현할 예정

Feat: 채팅 구현 (미완성)

---

client/src/components/views/BuyerPage/SellerMatch.jsx
server/app.js

2024.11.30 
SellerMatch, 백엔드 위치계산 수정

SellerMatch, 백엔드 위치계산 수정

---

client/src/components/views/BuyerPage/BuyMoney.jsx
client/src/components/views/BuyerPage/SellerMatch.jsx

- [ O] FE
<br/>
- BuyMoney, SellerMoney 헤더에 토큰 추가
<br/>
- 
<br/>
- 
<br/>

feat: 헤더에 토큰 추가

---

client/src/components/views/BuyerPage/SellerMatch.jsx
client/src/components/views/PostListPage/PostDetail.jsx
client/src/components/views/PostListPage/PostList.jsx

<br/>
- 추천 판매자 화면 UI와 수정함
- 판매 목록 화면 필터 구현 중
<br/>
- 판매 목록 화면 필터 마무리
- 
<br/>
- 
<br/>

feat: 추천판매자 화면 수정, 판매목록 필터 구현 중

---

server/app.js
server/middleware/refreshTokenMiddleware.js
server/models/user.js
server/services/authService.js
server/utils/jwt.js

<br/>
리프레시 토큰 로직 추가
<br/>
<br/>
- 
<br/>

feat: 토큰갱신추가(:refreshToken)

---

client/src/App.js
client/src/components/utils/api.jsx
client/src/components/views/BuyerPage/BuyMoney.jsx
client/src/components/views/BuyerPage/SellerMatch.jsx
client/src/components/views/LoginPage/Login.jsx
client/src/components/views/NavBar/NavBar.jsx
client/src/components/views/PostListPage/PostDetail.jsx
client/src/components/views/PostListPage/PostDetail2.jsx
client/src/components/views/PostListPage/PostList.jsx
client/src/components/views/SellerPage/SellMoney.jsx
server/middleware/refreshTokenMiddleware.js
server/services/authService.js

<br/>
- refrsh token 생성 안되는 오류 수정함
- 기존의 localhost:5000/ ~ 를 axios로 호출했던 것을 api로 변경
<br/>
- 마이페이지 
- 채팅
- 판매상세정보 사진 슬라이더 해결
<br/>
- 
<br/>

fix: refresh token 오류 해결, axios -> api 변경

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/PostListPage/PostDetail2.jsx
client/src/components/views/PostListPage/PostList.jsx

<br/>
- 도로명 주소를 동으로 변환
<br/>
<br/>
- 
<br/>

feat: 판매 목록 거래 위치  도로명 -> 동 변환

---

server/app.js
server/models/user.js
server/package-lock.json
server/package.json
server/routes/userRoutes.js
server/services/authService.js
server/services/userService.js
server/swagger.js
server/swagger/swagger-output.json
server/utils/calculate.js

<br/>
마이페이지 부분 백엔드 구현
<br/>
- 스키마 수정  - 환전 조회  - 기부 조회  - 기부 순위
<br/>
<br/>

feat: 마이페이지

---

server/app.js
server/routes/paths.js
server/routes/sellRoutes.js
server/routes/tradeRoutes.js
server/swagger/swagger-output.json

<br/>
: 마이페이지>내 판매 구현
<br/>
: 환전 조회
<br/>
- 모든 라우터 base path '/api' 추가 필요
<br/>

내 판매 목록 추가 && api path 분리

---

client/src/components/views/BuyerPage/BuyMoney.jsx
client/src/components/views/BuyerPage/SellerMatch.jsx
client/src/components/views/MyPage/MySell.jsx
server/routes/tradeRoutes.js

<br/>
- SellerMatch 백엔드 연결 완료
- SellerMatch에 도로명 -> 동 변환 함수 추가
<br/>
<br/>
- 
<br/>

feat: SellerMatch 백엔드 연결

---

client/src/components/views/BuyerPage/SellerMatch.jsx
server/routes/tradeRoutes.js

<br/>
- SellerMatch api 호출시 이미지와 location도 리턴
- 내가 올린 판매글 제외하고 sellermatch되도록 구현
<br/>
- sellermatch부분... location이 다름에도 동변환이 동일하게 되는 문제 해결
<br/>
- 
<br/>

feat: sellermatch img, location전송, sellerid로 필터

---

client/src/components/views/BuyerPage/SellerMatch.jsx

<br/>
- SellerMatch 동 변환이 동일하게 됐던 에러 해결
- seller id 대신 location 기준으로 변환
<br/>
<br/>
- 
<br/>

fix: SellerMatch 동 변환 에러 해결

---

server/models/user.js
server/routes/sellRoutes.js
server/services/userService.js

<br/>
판매 목록에서 거리 반환 -- 변수명 : distance
<br/>
<br/>
- 
<br/>

feat: 프론트측 요청사항 구현(2)

---

client/src/components/views/LoginPage/Login.jsx
client/src/components/views/PostListPage/PostDetail.jsx
server/routes/authRoutes.js
server/services/authService.js

feat: 본인의 판매글만 삭제 가능하도록 구현

---

server/app.js
server/package-lock.json
server/package.json
server/routes/sellRoutes.js
server/utils/socketServer.js

<br/>
<br/>
<br/>
- 추천판매자 페이지에서 해당 판매 누르면 postDetail로 넘어가서 문의하기 누르면 채팅 시작 필요
- 문의하기 누르면 sell/sellselect 로 들어가서 buyer에 등록되어야하고 채팅에도 추가되어야함
- 판매자가 판매상태 변경 시 백과 연결해서 db상태 업데이트 필요
<br/>

feat: 채팅 초기 구현 && 판매자 판매 상태 변경

---

client/src/components/views/ChattingPage/Chat2.jsx
client/src/components/views/PostListPage/PostDetail.jsx
server/package-lock.json
server/routes/sellRoutes.js

<br/>
- 자기가 올린 판매상세 글은 채팅 버튼 못 누르게 함
<br/>
-
<br/>
- 현재 sellSelect api 호출 에러, 채팅 시작 실패 에러
-  console.log("MongoDB ObjectId 변환 가능 여부:", mongoose.Types.ObjectId.isValid(buyerId)); 에서 false 나오는 상황
- req.user.id 값이 문자열일 가능성이 높아, 이를 MongoDB ObjectId로 변환해야 한다고 함,,,....
<br/>

feat: from PostDetail to Chat (에러해결필요)

---

client/package-lock.json
client/package.json
client/src/components/views/DonatePage/DonateRegister.jsx
client/src/components/views/PostListPage/PostDetail.jsx
client/src/socket.js
server/app.js
server/routes/chatRoutes.js
server/routes/paths.js
server/routes/sellRoutes.js
server/routes/tradeRoutes.js
server/utils/socketServer.js

<br/>
sellerSelect 에러 해결 및 채팅 연결
<br/>
채팅기능 완료
<br/>
-기부 전달 데이터 형식 확정 필요
<br/>

feat: 채팅 연결

---

client/src/components/views/MyPage/MySell.jsx
client/src/components/views/PostListPage/PostList.jsx
server/routes/sellRoutes.js

<br/>
- postlist, mysells에 거래상태 태그 추가함
- mysells는 확인못해봄
<br/>
<br/>
- 
<br/>

feat: PostList, MySells에 거래 상태 태그 추가

---

client/src/components/views/PostListPage/PostDetail.jsx
server/package.json
server/routes/chatRoutes.js
server/routes/sellRoutes.js
server/swagger.js
server/swagger/swagger-output.json

<br/>
<br/>
채팅 목록 
<br/>
- sellSelect updatedSell 객체 반환 삭제
- sellSelect 판매자 정보 반환 추가
- buyerImg : 판매자 프로필 사진
- currency : 판매 통화 종류
- amount : 판매 금액
<br/>

feat: sellSelect 응답구조 변경 && fix: mySells 에러 수정  & 스웨거 수정

---

server/routes/chatRoutes.js

<br/>
sellDescription -> sellImg : sell에 등록된 첫번째 사진
<br/>
<br/>
- 
<br/>

fix: sellSelect 응답 데이터 추가

---

server/routes/donationRoutes.js

<br/>
기부등록 라우터 에러 해결
<br/>
<br/>
- 지금 연락처, 회사이름 하드코딩 되어있음 수정 필요
- 화폐종류를 받아서 한국돈으로 프론트에서 변환해서 주는것 아니였는지 확인 필요 (지금 그래서 donation스키마에 화폐종류 필드 없음)
- 이미지가 프론트에서 백으로 안넘어오는 문제 해결 필요
- 돈의 액수도 안넘어옴
<br/>

fix: fix bson error in dRegi

---

server/models/chatRoom.js
server/models/user.js
server/routes/chatRoutes.js
server/routes/sellRoutes.js
server/routes/tradeRoutes.js
server/services/chatService.js
server/utils/calculate.js

<br/>
1. 채팅 리스트 구현
2. 채팅방 db 생성
<br/>
채팅 메세지 redis에 저장하기
<br/>
- 
<br/>

feat: add chatList

---

server/routes/chatRoutes.js
server/services/chatService.js
server/utils/calculate.js

<br/>
중간 위치 기반 장소 추천 기능 구현
<br/>
<br/>
- 프론트 연결 후 에러 발생 시 해당 내용 전달 필요 
<br/>

feat: add placeRecommendation

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/PostListPage/PostDetail.jsx
server/routes/chatRoutes.js
server/services/chatService.js

<br/>
장소 추천 기능 에러 수정 
- 카카오맵 api 연동 에러 fix
- 판매자, 구매자 정보 반환 에러 fix
- 프론트에서 chatRoomId 안넘어오는 에러 fix
<br/>
<br/>
- 회원가입 했을 때 따로 추가적으로 주소를 저장하는 로직이 없어서 구매자가 바로 구매를 원할 경우 주소가 null로 처리되어 에러 발생
<br/>

fix: 장소추천기능수정_1

---

server/routes/sellRoutes.js
server/services/chatService.js
server/services/userService.js

<br/>
판매자의 경우 판매 등록을 수행할 시 trade_address가 null인 경우 등록 시에 입력한 주소를 자동으로 user에 업데이트
<br/>
<br/>
- 
<br/>

fix: 주소 null 오류 수정

---

server/routes/chatRoutes.js
server/services/chatService.js
server/services/userService.js
server/utils/calculate.js

<br/>
거래장소 추천기능 에러 해결
주소 업데이트 위도 미저장 에러해결
<br/>
<br/>
- 거래 장소 추천 라우터 응답 형식
<br/>

fix: 거래장소 추천기능 && 주소 업데이트 위도 미저장 에러 해결

---

client/src/components/views/BuyerPage/SellerMatch.jsx
server/middleware/authMiddleware.js
server/routes/tradeRoutes.js

<br/>
구매자가 추천 받기 누를 시에 주소를 입력하면 tradeAddress null인 경우 해당 주소로 update
<br/>
<br/>
- 
<br/>

feat: 추천 받기 중 주소 업데이트 로직 추가

---

server/routes/chatRoutes.js
server/services/chatService.js

<br/>
채팅방 안에서 상대의 정보를 가져오는 로직 생성
<br/>
<br/>
- 
<br/>

feat: 채팅방에서 상대의 정보 가져오기

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/ChattingPage/PlaceModal.jsx
client/src/components/views/MyPage/MyPage.jsx
server/services/chatService.js

<br/>
- 상대 정보 뜨도록 채팅방에서
<br/>
<br/>
- 
<br/>

feat: 상대 정보 뜨도록

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/ChattingPage/ChatList.jsx
client/src/components/views/ChattingPage/PlaceModal.jsx
client/src/components/views/MyPage/MyPage.jsx
client/src/components/views/PostListPage/PostList.jsx

<br/>
- 거래장소추천 전송 누르면 정적지도url로 이동할 수 있도록 구현
- 거래장소추천 메시지만 스타일 색상 다르게
- 마이페이지 아이폰se 스크롤 가능하도록
- postlist 원환환산금액 마진 수정
<br/>
<br/>
- 
<br/>

feat: 채팅에 동적 지도 url 추가

---

client/src/components/views/ChattingPage/Chat.jsx

fix: 변수명변경

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/PostListPage/PostDetail.jsx
server/configs/redis.js
server/package-lock.json
server/package.json
server/routes/chatRoutes.js
server/services/redisService.js
server/utils/socketServer.js

<br/>
기능에서 어떤 부분이 구현되었는지 설명해주세요
- 채팅기능 Redis와 연결
<br/>
채팅 기능 마무리
<br/>
- 
<br/>

feat: Redis 연결

---

server/routes/chatRoutes.js
server/services/redisService.js

<br/>
redis에서 해당 채팅방의 채팅 내역 불러오기
<br/>
<br/>
- 지금은 최근에 보낸 순으로 sort 되어있는데 반대로 해야하나? 정렬 기준 논의 필요 
<br/>

feat: 채팅 내역 불러오기

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/PostListPage/PostDetail.jsx
client/src/components/views/PostListPage/PostList.jsx
server/configs/redis.js

<br/>
- 메시지 수신 발신 연결
<br/>
<br/>
- 
<br/>

feat: 메시지 수신 발신 연결

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/ChattingPage/ChatList.jsx

<br/>
- 채팅 스타일 수정
- flex-start, end적용
<br/>
<br/>
- 
<br/>

style: 채팅 메시지 스타일 수정

---

client/src/components/views/ChattingPage/Chat.jsx

<br/>
- 채팅에서 판매정보 불러오는 부분에서 여러 이미지일 경우 에러 나는 거 해결
- 
<br/>
<br/>
- 
<br/>

feat: 여러 이미지일 경우 첫 번째만 받아오도록

---

client/src/components/views/PostListPage/PostDetail.jsx
server/routes/tradeRoutes.js
server/services/chatService.js

<br/>
기능에서 어떤 부분이 구현되었는지 설명해주세요
- 채팅목록에서 redis의 마지막 채팅가져와서 최신순 정렬
<br/>
<br/>
- 
<br/>

feat: 채팅목록 대화 최신순정렬

---

server/configs/redis.js
server/routes/chatRoutes.js
server/routes/donationRoutes.js
server/routes/historyRoutes.js
server/routes/paths.js
server/services/chatService.js
server/services/donationService.js
server/services/historyService.js

<br/>
기능에서 어떤 부분이 구현되었는지 설명해주세요
- redis user .env로 옮김
- 환전 조회 로직 추가
<br/>
<br/>
http://localhost:5000/api/history/exchange
<br/>

feat: 환전 조회 기능

---

client/src/components/views/MyPage/MyExchange.jsx
client/src/components/views/PostListPage/PostDetail.jsx

<br/>
- 환전 내역 백엔드 연결 중 , 
- 에러 발생
<br/>
<br/>
- 
<br/>

feat: 환전 내역 백엔드 연결 중

---

client/src/components/views/MyPage/MyExchange.jsx

<br/>
- 환전 내역 스타일 수정 완료
<br/>
<br/>
- 
<br/>

style: 환전 내역 스타일 수정

---

client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/PostListPage/PostDetail.jsx

<br/>
- 채팅 말풍선 가운데 정렬되는 문제 해결
<br/>
<br/>
- 
<br/>

style: 채팅 말풍선 가운데 정렬 에러 해결

---

server/routes/donationRoutes.js
server/services/donationService.js
server/services/redisService.js

<br/>
기부랭킹, 기부조회마무리
<br/>
<br/>
- /api/donation/rank
- /api/donation/total
<br/>

feat: 기부기능

---

server/models/donation.js
server/routes/donationRoutes.js
server/services/donationService.js

<br/>
기부 상태 로직 추가
<br/>
<br/>
- 
<br/>

feat: 기부 상태 로직 추가

---

server/routes/donationRoutes.js
server/routes/historyRoutes.js
server/services/donationService.js
server/services/historyService.js

<br/>
기부 목록 조회, 상태별 기부 처리 현황 조회
<br/>
<br/>
환전 내역 조회 시 당시의 원화 가치 전달 - 프론트와 논의 필요
<전달사항>
- /api/donation/donationProcess - 상태별 기부조회
- /api/history/donations - 기부 내역 조회
<br/>

feat: 기부목록

---

client/src/components/views/PostListPage/PostList.jsx

style: 모달 위치 수정

---

server/Dockerfile

<br/>
numpy 버전 오류 해결 torch와 호환
<br/>
<br/>
- 
<br/>

fix: numpy 버전 오류

---

server/routes/authRoutes.js

<br/>
카카오 로그인 리다이렉트 로컬호스트로 가는 오류 수정
<br/>
<br/>
- 
<br/>

fix: kakaoRedirect path

---

client/src/components/utils/api.jsx
client/src/components/views/ChattingPage/Chat.jsx
client/src/components/views/LoginPage/Login.jsx
client/src/components/views/ModelPage/Detect.jsx
client/src/setupProxy.js
client/src/socket.js
server/routes/authRoutes.js
server/swagger/swagger-output.json
server/utils/socketServer.js

<br/>
https오류
<br/>
<br/>
- 
<br/>

fix: https오류

---

server/app.js

fix: cors 주소 에러 수정

---

server/models/chatRoom.js
server/routes/chatRoutes.js
server/routes/sellRoutes.js
server/services/chatService.js

<br/>
> chatRoomId 중복 처리 로직 추가
> chatRoom deleteMany설정 추가
<br/>
<br/>
- 
<br/>

fix: chatRoomId duplicate error

---

server/routes/authRoutes.js

fix: googleLoginRedirectUrl error

---

server/services/chatService.js

fix: chatRoomId castError

---

server/routes/chatRoutes.js
server/services/chatService.js

<br/>
isChat 조건 범위 넓어서 모든 거래에 채팅방 있다고 뜨는 오류 해결
<br/>
<br/>
- 
<br/>

fix: isChat 조건 범위 수정

---

server/routes/chatRoutes.js

<br/>
sellselect 이후에도 '거래중'변환 실패 해결
<br/>
<br/>
- 
<br/>

fix: 판매 상태 업데이트

---

server/routes/tradeRoutes.js

fix: buyerInfo 안넘어가는 오류 해결

---

client/src/components/utils/KakaoMap.jsx
server/models/model.py

fix: model cors 에러 수정

---

client/src/components/views/BuyerPage/SellerMatch.jsx

fix: sellermatch body넘겨주기

---

client/src/components/views/Layout/Layout.jsx

style: sellermatch에 navbar추가
